---
title: "venn_diagram"
output: html_document
date: "2024-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Rtsne)
library(ggplot2)
```

## Venn Diagram

```{r venn}
library(VennDiagram)

sgcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/ressg/miRNA_score.csv')[1])
sngcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/rescv/miRNA_score.csv')[1])
ksshiba <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/resk/Exp_score.csv')[1])
dgcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/resdg/Exp_dgcca.csv')[1])

x <- list(
  A = sgcca, 
  B = sngcca, 
  C = ksshiba,
  D = dgcca
  )

# Helper function to display Venn diagram
display_venn <- function(x, ...){
  library(VennDiagram)
  grid.newpage()
  venn_object <- venn.diagram(x, filename = NULL, ...)
  grid.draw(venn_object)
}
ggvenn(
  x, 
  fill_color = c("#0073C2FF", 
                 "#EFC000FF", 
                 "#868686FF", 
                 "#CD534CFF"),
  stroke_size = 0.5, set_name_size = 4
  )

display_venn(
  x,
  category.names = c("Set 1" , 
                     "Set 2 " , 
                     "Set 3", 
                     "Set 4"),
  fill = c("#999999", 
           "#E69F00", 
           "#56B4E9", 
           "#009E73")
  )
```
```{r tsne}
y <- as.list(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/PAM50label664.txt"))$V1
exp <- t(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/Exp664.txt"))
expnames <- as.list(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/Exp664_genes.txt"))
colnames(exp) <- expnames$V1
sngcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/rescv/Exp_score.csv'))$Name
selected <- exp[,colnames(exp) %in% sngcca]

tsne <- Rtsne(as.matrix(selected), check_duplicates = FALSE, pca = TRUE,
              perplexity=30, theta=0.0, dims=2)

jiangwei <- as.data.frame(tsne$Y)

jiangwei$Class<-as.factor(y)

length(unique(jiangwei$Class))
mainPalette <- rainbow(4)

ggplot(jiangwei, aes(x=V1, y=V2, color=Class)) +
  geom_point(size=1.25) +
  labs(title = "t-SNE Plot",
       x = "DIM 1",
       y = "DIM 2") +
  theme(plot.title = element_text(hjust = 0.5))

#============================================================================================
meth <- t(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/Meth664.txt"))
RNAnames <- as.list(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/Meth664_probes.txt"))
colnames(meth) <- RNAnames$V1
sngcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/rescv/Meth_score.csv'))$Name
selected <- meth[,colnames(meth) %in% sngcca]

tsne <- Rtsne(as.matrix(selected), check_duplicates = FALSE, pca = TRUE,
              perplexity=30, theta=0.0, dims=2)

jiangwei <- as.data.frame(tsne$Y)

jiangwei$Class<-as.factor(y)

length(unique(jiangwei$Class))
mainPalette <- rainbow(4)

ggplot(jiangwei, aes(x=V1, y=V2, color=Class)) +
  geom_point(size=1.25) +
  labs(title = "t-SNE Plot",
       x = "DIM 1",
       y = "DIM 2") +
  theme(plot.title = element_text(hjust = 0.5))

#============================================================================================
miRNA <- t(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/miRNA664.txt"))
RNAnames <- as.list(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/miRNA664_miRNA.txt"))
colnames(miRNA) <- RNAnames$V1
sngcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/rescv/miRNA_score.csv'))$Name
selected <- miRNA[,colnames(miRNA) %in% sngcca]

tsne <- Rtsne(as.matrix(selected), check_duplicates = FALSE, pca = TRUE,
              perplexity=30, theta=0.0, dims=2)

jiangwei <- as.data.frame(tsne$Y)

jiangwei$Class<-as.factor(y)

length(unique(jiangwei$Class))
mainPalette <- rainbow(4)

ggplot(jiangwei, aes(x=V1, y=V2, color=Class)) +
  geom_point(size=1.25) +
  labs(title = "t-SNE Plot",
       x = "DIM 1",
       y = "DIM 2") +
  theme(plot.title = element_text(hjust = 0.5))

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
