---
title: "venn_diagram"
output: html_document
date: "2024-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Rtsne)
library(ggplot2)
```

## Venn Diagram

```{r venn}
library(VennDiagram)
library(ggvenn)
sgcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/ressg/Exp_score.csv')[1])$Name
sngcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/rescv/Exp_score.csv')[1])$Name
ksshiba <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/resk/Exp_score.csv')[1])$Name
dgcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/resdg/Exp_dgcca.csv')[1])$Name

x <- list(
  DGCCA = dgcca,
  KSSHIBA = ksshiba,
  SGCCA = sgcca, 
  SNGCCA = sngcca
  )

display_venn <- function(x, ...){
  library(VennDiagram)
  grid.newpage()
  venn_object <- venn.diagram(x, filename = NULL, ...)
  grid.draw(venn_object)
}
#names(x) <- c('DGCCA\n(1325)','KSSHIBA\n(311)', 'SGCCA\n(302)', 'SNGCCA\n(336)')
ggvenn(
  x, 
  show_percentage = F,
  fill_color = c("#1c92d2","#f7b733","#6b6b83", "#f12711"),
  stroke_size = 0.5, set_name_size = 4
  )

#display_venn(
#  x,
#  category.names = c("Set 1" , "Set 2 " , "Set 3", "Set 4"),
  #fill = c("#1c92d2","#f7b733","#6b6b83", "#f12711")
  #)
ggsave('FigVenna.eps')
ggsave('FigVenna.png')
sgcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/ressg/Meth_score.csv')[1])$Name
sngcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/rescv/Meth_score.csv')[1])$Name
ksshiba <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/resk/Meth_score.csv')[1])$Name
dgcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/resdg/Meth_dgcca.csv')[1])$Name

x <- list(
  DGCCA = dgcca,
  KSSHIBA = ksshiba,
  SGCCA = sgcca, 
  SNGCCA = sngcca
  )
#names(x) <- c('DGCCA\n(1650)','KSSHIBA\n(1725)', 'SGCCA\n(346)', 'SNGCCA\n(269)')
ggvenn(
  x, 
  show_percentage = F,
  fill_color = c("#1c92d2","#f7b733","#6b6b83", "#f12711"),
  stroke_size = 0.5, set_name_size = 4
  )
ggsave('FigVennb.eps')
ggsave('FigVennb.png')
sgcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/ressg/miRNA_score.csv')[1])$Name
sngcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/rescv/miRNA_score.csv')[1])$Name
ksshiba <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/resk/miRNA_score.csv')[1])$Name
dgcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/resdg/miRNA_dgcca.csv')[1])$Name

x <- list(
  DGCCA = dgcca,
  KSSHIBA = ksshiba,
  SGCCA = sgcca, 
  SNGCCA = sngcca
  )
#names(x) <- c('DGCCA\n(209)','KSSHIBA\n(222)', 'SGCCA\n(256)', 'SNGCCA\n(89)')
ggvenn(
  x, 
  show_percentage = F,
  fill_color = c("#1c92d2","#f7b733","#6b6b83", "#f12711"),
  stroke_size = 0.5, set_name_size = 4
  )
#"#88AEFA","#8CE6C2","#909DB7","#F8CF57","#998DFC","#9DDFF9","#B38CCE","#F7AE73"
ggsave('FigVennc.eps')
ggsave('FigVennc.png')
```
```{r tsne}
y <- as.list(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/PAM50label664.txt"))$V1
exp <- t(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/Exp664.txt"))
expnames <- as.list(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/Exp664_genes.txt"))
colnames(exp) <- expnames$V1
sngcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/rescv/Exp_score.csv'))$Name
selected <- exp[,colnames(exp) %in% sngcca]

tsne <- Rtsne(as.matrix(selected), check_duplicates = FALSE, pca = TRUE,
              perplexity=30, theta=0.0, dims=2)

jiangwei <- as.data.frame(tsne$Y)

jiangwei$Class<-as.factor(y)

length(unique(jiangwei$Class))
mainPalette <- rainbow(4)

ggplot(jiangwei, aes(x=V1, y=V2, color=Class)) +
  geom_point(size=1.25) +
  labs(title = "t-SNE Plot",
       x = "DIM 1",
       y = "DIM 2") +
  theme(plot.title = element_text(hjust = 0.5))

#============================================================================================
meth <- t(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/Meth664.txt"))
RNAnames <- as.list(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/Meth664_probes.txt"))
colnames(meth) <- RNAnames$V1
sngcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/ressg/Meth_score.csv'))$Name
selected <- meth[,colnames(meth) %in% sngcca]

tsne <- Rtsne(as.matrix(selected), check_duplicates = FALSE, pca = TRUE,
              perplexity=30, theta=0.0, dims=2)

jiangwei <- as.data.frame(tsne$Y)

jiangwei$Class<-as.factor(y)

length(unique(jiangwei$Class))
mainPalette <- rainbow(4)

ggplot(jiangwei, aes(x=V1, y=V2, color=Class)) +
  geom_point(size=1.25) +
  labs(title = "t-SNE Plot",
       x = "DIM 1",
       y = "DIM 2") +
  theme(plot.title = element_text(hjust = 0.5))

#============================================================================================
miRNA <- t(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/miRNA664.txt"))
RNAnames <- as.list(read.table("D:/GitHub/SNGCCA/SNGCCA/RealData/miRNA664_miRNA.txt"))
colnames(miRNA) <- RNAnames$V1
sngcca <- as.list(read.csv('D:/GitHub/SNGCCA/SNGCCA/RealData/rescv/miRNA_score.csv'))$Name
selected <- miRNA[,colnames(miRNA) %in% sngcca]

tsne <- Rtsne(as.matrix(selected), check_duplicates = FALSE, pca = TRUE,
              perplexity=30, theta=0.0, dims=2)

jiangwei <- as.data.frame(tsne$Y)

jiangwei$Class<-as.factor(y)

length(unique(jiangwei$Class))
mainPalette <- rainbow(4)

ggplot(jiangwei, aes(x=V1, y=V2, color=Class)) +
  geom_point(size=1.25) +
  labs(title = "t-SNE Plot",
       x = "DIM 1",
       y = "DIM 2") +
  theme(plot.title = element_text(hjust = 0.5))

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
