---
title: "Plot"
author: "RongWu"
date: "2023-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(openxlsx)
library(gridExtra)

```


```{r Fig1a}
data = read.csv('Fig1a_trans.csv')
sp = ggplot(data = data, aes(x=X,y=Y,color=Method)) + geom_point()

sp + facet_grid(Method ~ views) + theme_classic()+xlab("")+ylab("")+
  scale_color_manual(values = c("#f12711","#f5af19","#1c92d2"))+
  theme(strip.text.x = element_text(size=12),
        strip.text.y = element_text(size=12),
        strip.background = element_rect(colour='white', fill="white"),
        legend.position = 'none')
ggsave('Fig1a.eps')

```

```{r Fig1b}
data = read.csv('Fig1b_trans.csv')
sp = ggplot(data = data, aes(x=X,y=Y,color=Method)) + geom_point()

sp + facet_grid(Method ~ views) + theme_classic()+xlab("")+ylab("")+
  scale_y_continuous(limits = c(-2,2))+
  scale_x_continuous(limits = c(-2,2))+
  scale_color_manual(values = c("#f12711","#f5af19","#1c92d2"))+
  theme(strip.text.x = element_text(size=12),
        strip.text.y = element_text(size=12),
        strip.background = element_rect(colour='white', fill="white"),
        legend.position = 'none')
ggsave('Fig1b.eps')

```


